### ISSUE TITLE
Readme links to wrong blog post & question about schematics availability

### ISSUE THREAD

**Issue by mtfurlan** [viktak/Light-Panels#1]
Hey, you've made a really neat project and I'm thinking about making it with slight modifications to the electronics side to use up parts I have lying around.

1. Are you planning to/have you put the kicad files anywhere?
    I saw that in the blog post you planned to use it for multiple projects, so I looked at a few of your other repos but didn't see anything in my brief looking around.
2. The link in the readme is to the wrong blog post.

Thanks for the cool project and the good writeup.

**Comment by viktak** [comment]
Hi @mtfurlan ,

1. I'm afraid I can't share the kicad files at the moment. The schematics are available on my blog, from that the PCB can be easily recreated. The reason you haven't found the "other projects" is because they are not published yet. They are coming soon. This circuit can be used to drive **any** WS2812B, SK6812, etc based string of lights.
2. Thanks for the catch, it is now corrected.
